### PR TITLE
Add decimal to file sizes, fixes #51

### LINKED ISSUE #51: Allow decimal digits in rounded file sizes
When file sizes are being rounded (`fancyindex_exact_size` is disabled), it's not very useful to report a 4.9 GiB file as `4G`: it would actually be good to include a decimal digit and show the value as `4.9G`. This is specially true for magnitudes of MiB and bigger.

### PR DESCRIPTION
**Pull request by AndersTrier**
Hi!
Please have a look at this.
I decided to include .0 to make the precession explicit.
The units used are kibibyte/mebibyte/gibibyte/...
ex: https://en.wikipedia.org/wiki/Kibibyte

### CODE REVIEW

**Comment by aperezdc** [comment]
I will take a look at this soon, I've been some days without a computer.

**Comment by aperezdc** [comment]
Finally I got some spare time to properly review and try this patch. It's looking all good, and I will be super happy to merge. Could you add an unit test which sets `fancyindex_exact_size off` and checks whether the generated output is the expected? We may want to look into #56 first, so the HTML can be easily parsed, WDYT?

**Comment by aperezdc** [comment]
@AndersTrier: Could you please take a look at the previous comment? Thanks!

**Comment by AndersTrier** [comment]
Simple test added. I also found a pretty elegant solution for changing the nginx config for each test.

What do you think about using the KiB, MiB, ... units instead of KB, MB, ...?

**Comment by aperezdc** [comment]
@AndersTrier: The test is just perfect, let's merge this! As for using SI units, I myself prefer them, but let's add that in a separate commit, to not delay merging this PR any longer.

**Pull request merged**
